variables:
- name: zuluLinuxLatest
  value: '/usr/lib/jvm/zulu-11-azure-amd64' 
trigger:
  batch: true
  branches:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'
jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-16.04'    
    steps:
      - checkout: self
        clean: true
      - bash: |
          git config --global user.email "mastercoms@tutanota.de"
          git config --global user.name "mastercoms"  
        displayName: Configure Git
      - bash: ./glowkit p
        displayName: Apply Patches
      - bash: (cd Glowkit-Patched && mvn -T 1C -B dependency:go-offline)
        displayName: Download Maven Dependencies
        env:
          JAVA_HOME: $(zuluLinuxLatest)
        # TODO - Use caching once Azure implements it
      - bash: ./glowkit j
        displayName: Build & Test
        env:
          JAVA_HOME: $(zuluLinuxLatest)
      - task: PublishBuildArtifacts@1
        displayName: Publish Jar
        inputs:
          pathtoPublish: Glowkit-Patched/target/glowkit.jar
          artifactName: Glowkit
      - bash: |
          cd Glowkit-Patched &&\
          mvn -T 1C -B -s ../.circleci/maven.xml source:jar javadoc:jar &&\
          cd target &&\
          find . -regextype grep -regex '.*/glowkit.*\([0-9]\|SNAPSHOT\)-sources\.jar' | xargs -i cp {} glowkit-sources.jar &&\
          find . -regextype grep -regex '.*/glowkit.*\([0-9]\|SNAPSHOT\)-javadoc\.jar' | xargs -i cp {} glowkit-javadoc.jar
        displayName: Create Source & Javadoc Jars
      - task: PublishBuildArtifacts@1
        displayName: Publish Source Jar
        inputs:
          pathtoPublish: Glowkit-Patched/target/glowkit-sources.jar
          artifactName: Glowkit Sources
      - task: PublishBuildArtifacts@1
        displayName: Publish Javadoc Jar
        inputs:
          pathtoPublish: Glowkit-Patched/target/glowkit-javadoc.jar
          artifactName: Glowkit Javadoc
      - task: PublishBuildArtifacts@1
        displayName: Publish Full Build Output if Failed
        inputs:
          pathtoPublish: Glowkit-Patched/target
          artifactName: Build Target Folder        
        condition: failed()
      - task: PublishTestResults@1
        displayName: Publish Test Results
        inputs:
          pathtoPublish: Glowkit-Patched/target/surefire-reports
